# Generated by Django 5.0.1 on 2024-02-21 13:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('business_company', '0003_comapany_users'),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemErrors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_time', models.DateTimeField()),
                ('error_name', models.CharField(max_length=500)),
                ('error_traceback', models.TextField()),
                ('error_fix_status', models.BooleanField(default=False)),
                ('error_occured_for', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='business_company.comapany_users')),
            ],
            options={
                'verbose_name': 'System Error',
            },
        ),
    ]
