# Generated by Django 5.0.1 on 2024-02-21 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system_administrator', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='systemerrors',
            name='error_traceback',
            field=models.TextField(max_length=3000),
        ),
    ]
