# Generated by Django 5.0.1 on 2024-02-23 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system_administrator', '0002_alter_systemerrors_error_traceback'),
    ]

    operations = [
        migrations.AlterField(
            model_name='systemerrors',
            name='error_occured_for',
            field=models.TextField(blank=True, null=True),
        ),
    ]
