# Generated by Django 5.0.1 on 2025-01-26 21:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0005_alter_customer_profile_picture'),
        ('orders', '0002_remove_order_shipping_address_order_order_id_and_more'),
        ('products', '0013_alter_product_images_color_alter_product_images_size'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_ip', models.GenericIPAddressField(verbose_name='Device IP')),
                ('cart_total_amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Cart Total Amount')),
                ('cart_checkout_status', models.BooleanField(default=False, verbose_name='Cart Checkout Status')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('customer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Cart', to='customer.customer')),
            ],
            options={
                'verbose_name': 'Customer Cart',
                'verbose_name_plural': 'Customer Carts',
            },
        ),
        migrations.CreateModel(
            name='CartItems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='Quantity')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('cart_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.cart')),
                ('product_sku', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product_sku')),
            ],
        ),
    ]
