# Generated by Django 5.0.1 on 2025-01-30 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_alter_cart_customer_id_alter_cart_device_ip'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='cart_total_amount',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True, verbose_name='Cart Total Amount'),
        ),
    ]
