# Generated by Django 5.0.1 on 2025-02-15 11:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_alter_cart_cart_total_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordershippingaddress',
            name='order_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shipping_address', to='orders.order'),
        ),
    ]
