# Generated by Django 5.0.1 on 2025-02-15 11:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_alter_ordershippingaddress_order_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderpayment',
            name='order_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_details', to='orders.order'),
        ),
    ]
