# Generated by Django 5.0.1 on 2025-02-16 13:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0002_alter_coupon_discount_amount_and_more'),
        ('orders', '0006_alter_orderdetails_order_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderpayment',
            name='coupon_applied',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='coupon', to='customer.coupon'),
        ),
    ]
