# Generated by Django 5.0.1 on 2025-02-16 13:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0002_alter_coupon_discount_amount_and_more'),
        ('orders', '0007_orderpayment_coupon_applied'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderpayment',
            name='coupon_applied',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='coupon', to='customer.coupon'),
        ),
    ]
