# Generated by Django 5.0.1 on 2025-02-27 20:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0010_order_delivery_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderdetails',
            name='updated_by',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='orderpayment',
            name='updated_by',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ordershippingaddress',
            name='updated_by',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='updated_by',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='CancelOrderRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cancellation_reason', models.TextField()),
                ('cancellation_status', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('updated_by', models.JSONField(blank=True, null=True)),
                ('order_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cancel_order', to='orders.order')),
            ],
            options={
                'verbose_name': 'Cancel Order',
            },
        ),
    ]
