# Generated by Django 5.0.1 on 2025-03-05 16:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0016_deliverypartner'),
        ('products', '0018_remove_product_discount_existing_discounts'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='delivery_partner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='delivery_time', to='orders.deliverypartner'),
        ),
        migrations.AlterField(
            model_name='order',
            name='delivery_time',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='delivery_time', to='orders.deliverytime'),
        ),
        migrations.AlterField(
            model_name='orderdetails',
            name='product_sku',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.product_sku'),
        ),
    ]
