# Generated by Django 5.0.1 on 2025-01-28 11:10

import business_admin.models
import django.db.models.deletion
import django_resized.forms
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdminPermissions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('permission_name', models.CharField(max_length=100, unique=True)),
                ('permission_description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.JSONField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='AdminPositions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.JSONField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='BusinessAdminUser',
            fields=[
                ('admin_unique_id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('admin_full_name', models.CharField(max_length=100)),
                ('admin_user_name', models.CharField(max_length=100)),
                ('admin_avatar', django_resized.forms.ResizedImageField(blank=True, crop=None, force_format=None, keep_meta=True, null=True, quality=-1, scale=None, size=[244, 244], upload_to=business_admin.models.get_admin_avatar_path)),
                ('admin_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('admin_contact_no', models.CharField(blank=True, max_length=20, null=True)),
                ('admin_is_superuser', models.BooleanField(default=False)),
                ('admin_account_created_at', models.DateTimeField(auto_now_add=True)),
                ('last_login_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.JSONField(blank=True, null=True)),
                ('admin_position', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='business_admin.adminpositions')),
            ],
            options={
                'verbose_name': 'Admin User',
                'verbose_name_plural': 'Admin Users',
            },
        ),
        migrations.CreateModel(
            name='ActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=500)),
                ('details', models.JSONField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('activity_done_by_admin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_logs', to='business_admin.businessadminuser')),
            ],
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_token', models.CharField(max_length=255, unique=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('device_details', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('admin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='business_admin.businessadminuser')),
            ],
        ),
        migrations.CreateModel(
            name='AdminRolePermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.JSONField(blank=True, null=True)),
                ('permission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='role_permissions', to='business_admin.adminpermissions')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='role_permissions', to='business_admin.adminpositions')),
            ],
            options={
                'unique_together': {('role', 'permission')},
            },
        ),
    ]
