# Generated by Django 5.0.1 on 2025-01-21 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business_admin', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='adminpermissions',
            name='updated_by',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='adminpositions',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='adminpositions',
            name='updated_by',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='adminrolepermission',
            name='updated_by',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='businessadminuser',
            name='updated_by',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
