# Generated by Django 5.0.1 on 2025-01-29 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business_admin', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='businessadminuser',
            name='admin_is_superuser',
        ),
        migrations.RemoveField(
            model_name='businessadminuser',
            name='last_login_at',
        ),
        migrations.AlterField(
            model_name='businessadminuser',
            name='admin_email',
            field=models.EmailField(default=9, max_length=254),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='businessadminuser',
            name='admin_user_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
