# Generated by Django 5.0.1 on 2025-02-03 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business_admin', '0002_remove_businessadminuser_admin_is_superuser_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='device_details',
            field=models.JSONField(default={}),
            preserve_default=False,
        ),
    ]
