# Generated by Django 5.0.1 on 2025-01-21 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business_admin', '0002_adminpermissions_updated_by_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adminpermissions',
            name='updated_by',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='adminpositions',
            name='updated_by',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='adminrolepermission',
            name='updated_by',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='businessadminuser',
            name='updated_by',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
