# Generated by Django 5.0.1 on 2025-02-03 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business_admin', '0003_alter_session_device_details'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='session',
            name='session_token',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
