# Generated by Django 5.0.1 on 2025-01-21 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business_admin', '0004_businessadminuser_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='businessadminuser',
            name='admin_is_staff',
        ),
        migrations.AddField(
            model_name='businessadminuser',
            name='admin_user_name',
            field=models.CharField(default='saki', max_length=100),
            preserve_default=False,
        ),
    ]
