# Generated by Django 5.0.1 on 2025-01-21 19:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business_admin', '0005_remove_businessadminuser_admin_is_staff_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='businessadminuser',
            name='admin_position',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='business_admin.adminpositions'),
        ),
    ]
