# Generated by Django 5.0.1 on 2025-02-04 16:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business_admin', '0005_adminuserrole'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='activitylog',
            old_name='activity_done_by_admin',
            new_name='activity_done_by_business_admin',
        ),
        migrations.AddField(
            model_name='activitylog',
            name='activity_done_by_dev_admin',
            field=models.ForeignKey(default=5, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
