# Generated by Django 5.0.1 on 2025-01-22 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business_admin', '0006_alter_businessadminuser_admin_position'),
    ]

    operations = [
        migrations.AlterField(
            model_name='businessadminuser',
            name='admin_user_name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
