# Generated by Django 5.0.1 on 2025-02-04 16:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business_admin', '0006_rename_activity_done_by_admin_activitylog_activity_done_by_business_admin_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='activitylog',
            name='activity_done_by_business_admin',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='audit_logs', to='business_admin.businessadminuser'),
        ),
        migrations.AlterField(
            model_name='activitylog',
            name='activity_done_by_dev_admin',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
