# Generated by Django 5.0.1 on 2025-01-22 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business_admin', '0007_alter_businessadminuser_admin_user_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='businessadminuser',
            name='admin_user_name',
            field=models.CharField(max_length=100),
        ),
    ]
