# Generated by Django 5.0.1 on 2025-02-04 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business_admin', '0008_alter_businessadminuser_admin_position'),
    ]

    operations = [
        migrations.AlterField(
            model_name='businessadminuser',
            name='admin_full_name',
            field=models.CharField(max_length=500),
        ),
    ]
