# Generated by Django 5.0.1 on 2025-01-22 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business_admin', '0008_alter_businessadminuser_admin_user_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='adminpermissions',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='adminrolepermission',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='businessadminuser',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
