# Generated by Django 5.0.1 on 2025-01-27 12:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('business_admin', '0009_adminpermissions_updated_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='businessadminuser',
            name='user',
        ),
    ]
