# Generated by Django 5.0.1 on 2025-02-06 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business_admin', '0009_alter_businessadminuser_admin_full_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='businessadminuser',
            name='admin_unique_id',
            field=models.CharField(max_length=500, primary_key=True, serialize=False),
        ),
    ]
