# Generated by Django 5.0.1 on 2025-02-06 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business_admin', '0010_alter_businessadminuser_admin_unique_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='businessadminuser',
            name='admin_full_name',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='businessadminuser',
            name='admin_unique_id',
            field=models.CharField(max_length=1000, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='businessadminuser',
            name='admin_user_name',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
