# Generated by Django 5.0.1 on 2025-01-27 16:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('business_admin', '0011_businessadminuser_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='businessadminuser',
            name='user',
        ),
    ]
