# Generated by Django 5.0.1 on 2025-02-07 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business_admin', '0011_alter_businessadminuser_admin_full_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='adminuserrole',
            name='updated_by',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
