# Generated by Django 5.0.1 on 2025-02-08 18:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business_admin', '0014_alter_adminuserrole_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adminuserrole',
            name='role',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='users', to='business_admin.adminpositions'),
        ),
    ]
