# Generated by Django 5.0.1 on 2025-02-08 22:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('business_admin', '0015_alter_adminuserrole_role'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Session',
        ),
    ]
