# Generated by Django 5.0.1 on 2025-02-15 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business_admin', '0016_delete_session'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adminpositions',
            name='name',
            field=models.CharField(choices=[('Business Owner', 'business owner')], max_length=100, unique=True),
        ),
    ]
