# Generated by Django 5.0.1 on 2025-02-15 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business_admin', '0017_alter_adminpositions_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adminpositions',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
