# Generated by Django 5.0.1 on 2025-02-18 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business_admin', '0018_alter_adminpositions_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='adminuserrole',
            name='extra_permissions',
            field=models.ManyToManyField(blank=True, related_name='extra_user_permissions', to='business_admin.adminpermissions'),
        ),
    ]
