# Generated by Django 5.0.1 on 2025-03-01 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business_admin', '0019_adminuserrole_extra_permissions'),
    ]

    operations = [
        migrations.AddField(
            model_name='businessadminuser',
            name='login_request',
            field=models.BooleanField(default=False),
        ),
    ]
