# Generated by Django 5.0.1 on 2025-01-11 06:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='errorlogs',
            options={'verbose_name': 'Error Log', 'verbose_name_plural': 'Error Logs'},
        ),
    ]
