# Generated by Django 5.0.1 on 2025-01-11 06:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0002_alter_errorlogs_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='errorlogs',
            options={'ordering': ['-timestamp'], 'verbose_name': 'Error Log', 'verbose_name_plural': 'Error Logs'},
        ),
    ]
