# Generated by Django 5.0.1 on 2025-01-28 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0002_alter_accounts_options_alter_accounts_first_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accounts',
            name='first_name',
            field=models.CharField(blank=True, max_length=50, verbose_name='First Name'),
        ),
    ]
