# Generated by Django 5.0.1 on 2025-02-16 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0005_alter_notification_to'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='notification',
            name='link',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
    ]
