# Generated by Django 5.0.1 on 2025-02-17 17:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0006_alter_notification_description_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='to',
        ),
        migrations.AddField(
            model_name='notification',
            name='to',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
