# Generated by Django 5.0.1 on 2025-03-01 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0008_remove_notification_read_remove_notification_to_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailAccounts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Friendly name for this email account', max_length=100)),
                ('email_address', models.EmailField(help_text='Email address to send from', max_length=100)),
                ('smtp_server', models.CharField(help_text='SMTP server address', max_length=100)),
                ('smtp_port', models.IntegerField(default=587, help_text='SMTP server port')),
                ('username', models.CharField(blank=True, help_text='SMTP username', max_length=100, null=True)),
                ('password', models.CharField(help_text='SMTP password', max_length=100)),
                ('use_tls', models.BooleanField(default=True, help_text='Use TLS for connection')),
                ('use_ssl', models.BooleanField(default=False, help_text='Use SSL for connection')),
                ('is_active', models.BooleanField(default=True, help_text='Is this account active?')),
            ],
            options={
                'verbose_name': 'Email Account',
                'verbose_name_plural': 'Email Accounts',
            },
        ),
        migrations.CreateModel(
            name='EmailTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Template name', max_length=100)),
                ('subject', models.CharField(help_text='Email subject', max_length=200)),
                ('body_text', models.TextField(help_text='Plain text email body')),
                ('body_html', models.TextField(blank=True, help_text='HTML email body', null=True)),
                ('purpose', models.CharField(choices=[('marketing', 'Marketing Emails'), ('transactional', 'Transactional Emails'), ('notification', 'Notification Emails'), ('support', 'Support Emails'), ('auth', 'Authentication'), ('other', 'Other')], help_text='Template purpose', max_length=20)),
            ],
        ),
    ]
