# Generated by Django 5.0.1 on 2025-03-02 22:44

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0010_emailaccounts_purpose_alter_emailaccounts_password_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteVisitor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(max_length=255)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True, null=True)),
                ('referrer', models.TextField(blank=True, null=True)),
                ('landing_page', models.CharField(blank=True, max_length=255, null=True)),
                ('visit_datetime', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_mobile', models.BooleanField(default=False)),
                ('is_tablet', models.BooleanField(default=False)),
                ('is_pc', models.BooleanField(default=False)),
                ('browser', models.CharField(blank=True, max_length=100, null=True)),
                ('os', models.CharField(blank=True, max_length=100, null=True)),
                ('country', models.CharField(blank=True, max_length=100, null=True)),
                ('city', models.CharField(blank=True, max_length=100, null=True)),
                ('visit_count', models.PositiveIntegerField(default=1)),
                ('duration_seconds', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Site Visitor',
                'verbose_name_plural': 'Site Visitors',
            },
        ),
        migrations.CreateModel(
            name='PageView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_url', models.CharField(max_length=255)),
                ('page_title', models.CharField(blank=True, max_length=255, null=True)),
                ('view_datetime', models.DateTimeField(default=django.utils.timezone.now)),
                ('time_on_page', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('is_bounce', models.BooleanField(default=False)),
                ('visitor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='page_views', to='system.sitevisitor')),
            ],
            options={
                'verbose_name': 'Page View',
                'verbose_name_plural': 'Page Views',
            },
        ),
        migrations.AddIndex(
            model_name='sitevisitor',
            index=models.Index(fields=['visit_datetime'], name='system_site_visit_d_f4b944_idx'),
        ),
        migrations.AddIndex(
            model_name='sitevisitor',
            index=models.Index(fields=['session_id'], name='system_site_session_83b18b_idx'),
        ),
        migrations.AddIndex(
            model_name='sitevisitor',
            index=models.Index(fields=['ip_address'], name='system_site_ip_addr_2ae1f1_idx'),
        ),
        migrations.AddIndex(
            model_name='pageview',
            index=models.Index(fields=['view_datetime'], name='system_page_view_da_3ccabf_idx'),
        ),
        migrations.AddIndex(
            model_name='pageview',
            index=models.Index(fields=['page_url'], name='system_page_page_ur_7041ca_idx'),
        ),
    ]
