# Generated by Django 5.0.1 on 2024-02-09 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Business_Identity',
            fields=[
                ('platform_product_key', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('business_name', models.CharField(max_length=100)),
                ('business_logo', models.ImageField(blank=True, null=True, upload_to='company_files/identity/')),
                ('business_description', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Business Identity',
            },
        ),
    ]
