# Generated by Django 5.0.1 on 2024-02-21 08:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('business_company', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='business_identity',
            options={'verbose_name': 'Business Identity', 'verbose_name_plural': 'Business Identities'},
        ),
    ]
