# Generated by Django 5.0.1 on 2025-02-09 11:29

import business_company.models
import django_resized.forms
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('business_company', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='business_identity',
            name='business_logo',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format=None, keep_meta=True, null=True, quality=-1, scale=None, size=[632, 632], upload_to=business_company.models.get_business_logo_image_path),
        ),
    ]
