# Generated by Django 5.0.1 on 2024-02-21 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business_company', '0002_alter_business_identity_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comapany_Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('email', models.EmailField(blank=True, max_length=254, null=True, unique=True)),
                ('is_super_user', models.BooleanField(default=False)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_employee', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Company User',
            },
        ),
    ]
