# Generated by Django 5.0.1 on 2024-02-23 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business_company', '0003_comapany_users'),
    ]

    operations = [
        migrations.AddField(
            model_name='comapany_users',
            name='employee_id',
            field=models.CharField(default=None),
        ),
        migrations.AddField(
            model_name='comapany_users',
            name='phone_number',
            field=models.CharField(blank=True, default=None, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='comapany_users',
            name='first_name',
            field=models.CharField(default=None, max_length=50),
        ),
        migrations.AlterField(
            model_name='comapany_users',
            name='last_name',
            field=models.CharField(default=None, max_length=50),
        ),
    ]
