# Generated by Django 5.0.1 on 2024-02-21 08:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.TextField()),
            ],
            options={
                'verbose_name': 'Product',
            },
        ),
        migrations.CreateModel(
            name='Product_Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=400, verbose_name='Product Category')),
            ],
            options={
                'verbose_name': 'Product Category',
            },
        ),
        migrations.CreateModel(
            name='Product_type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=400, verbose_name='Product Type')),
            ],
            options={
                'verbose_name': 'Product Type',
            },
        ),
        migrations.CreateModel(
            name='Product_Sub_Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sub_category', models.CharField(max_length=400, verbose_name='Product Sub-Category')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product_category')),
            ],
            options={
                'verbose_name': 'Product Sub-Category',
            },
        ),
        migrations.AddField(
            model_name='product_category',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product_type'),
        ),
    ]
