# Generated by Django 5.0.1 on 2025-02-06 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product_sku',
            name='product_color',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='product_sku',
            name='product_size',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='product_sku',
            name='product_sku',
            field=models.CharField(max_length=1000, unique=True),
        ),
    ]
