# Generated by Django 5.0.1 on 2024-02-23 17:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product_Brands',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand_name', models.CharField(max_length=300)),
                ('brand_logo', models.ImageField(blank=True, null=True, upload_to='brand_logos/')),
                ('brand_description', models.TextField(blank=True, null=True)),
                ('brand_origin', models.CharField(blank=True, max_length=200, null=True)),
            ],
            options={
                'verbose_name': 'Brand Informations',
            },
        ),
        migrations.AddField(
            model_name='product',
            name='product_offer_price',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='product',
            name='product_price',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='product',
            name='product_stock_status',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='inventory.product_stock_status'),
        ),
        migrations.AddField(
            model_name='product',
            name='product_brand',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='products.product_brands'),
        ),
    ]
