# Generated by Django 5.0.1 on 2025-02-11 21:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_product_sku_product_color_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product_discount',
            name='brand_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='products.product_brands'),
        ),
        migrations.AddField(
            model_name='product_discount',
            name='category_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='products.product_category'),
        ),
        migrations.AddField(
            model_name='product_discount',
            name='sub_category_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='products.product_sub_category'),
        ),
        migrations.AlterField(
            model_name='product_discount',
            name='product_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='products.product'),
        ),
    ]
