# Generated by Django 5.0.1 on 2025-01-09 20:03

import datetime
import django.db.models.deletion
import django_resized.forms
import products.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_product_brands_product_product_offer_price_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product_Colors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_color_code', models.CharField(max_length=50)),
                ('product_color_name', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Product Color',
                'verbose_name_plural': 'Product Colors',
            },
        ),
        migrations.CreateModel(
            name='Product_Flavours',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_flavour_name', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Product Flavour',
                'verbose_name_plural': 'Product Flavours',
            },
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name': 'Product', 'verbose_name_plural': 'Products'},
        ),
        migrations.AlterModelOptions(
            name='product_brands',
            options={'verbose_name': 'Brand', 'verbose_name_plural': 'Brands'},
        ),
        migrations.AlterModelOptions(
            name='product_category',
            options={'verbose_name': 'Product Category', 'verbose_name_plural': 'Product Categories'},
        ),
        migrations.AlterModelOptions(
            name='product_sub_category',
            options={'verbose_name': 'Product Sub-Category', 'verbose_name_plural': 'Product Sub-Categories'},
        ),
        migrations.AlterModelOptions(
            name='product_type',
            options={'verbose_name': 'Product Type', 'verbose_name_plural': 'Product Types'},
        ),
        migrations.RenameField(
            model_name='product',
            old_name='product_offer_price',
            new_name='product_description',
        ),
        migrations.RenameField(
            model_name='product_category',
            old_name='type',
            new_name='product_type',
        ),
        migrations.RemoveField(
            model_name='product',
            name='product_stock_status',
        ),
        migrations.RemoveField(
            model_name='product_brands',
            name='brand_origin',
        ),
        migrations.RemoveField(
            model_name='product_category',
            name='category',
        ),
        migrations.RemoveField(
            model_name='product_sub_category',
            name='category',
        ),
        migrations.RemoveField(
            model_name='product_sub_category',
            name='sub_category',
        ),
        migrations.AddField(
            model_name='product',
            name='product_category',
            field=models.ManyToManyField(to='products.product_category'),
        ),
        migrations.AddField(
            model_name='product',
            name='product_created_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 1, 9, 20, 2, 16, 574022, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='product_ingredients',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='product_stock_quantity',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='product',
            name='product_sub_category',
            field=models.ManyToManyField(to='products.product_sub_category'),
        ),
        migrations.AddField(
            model_name='product',
            name='product_usage_direction',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='product_brands',
            name='brand_country',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Brand Origin Country'),
        ),
        migrations.AddField(
            model_name='product_brands',
            name='brand_established_year',
            field=models.IntegerField(default=2000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product_brands',
            name='is_own_brand',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product_category',
            name='category_name',
            field=models.CharField(default='Makeup', max_length=40, verbose_name='Product Category'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product_category',
            name='description',
            field=models.CharField(default='GGEZ', max_length=400, verbose_name='Description of Product Category'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product_sub_category',
            name='category_id',
            field=models.ManyToManyField(to='products.product_category'),
        ),
        migrations.AddField(
            model_name='product_sub_category',
            name='description',
            field=models.CharField(default='GGEZ', max_length=400, verbose_name='Description of Product Sub-Category'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product_sub_category',
            name='sub_category_name',
            field=models.CharField(default='Face', max_length=40, verbose_name='Product Sub-Category'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product_type',
            name='description',
            field=models.CharField(default='GG', max_length=400, verbose_name='Description of Product Type'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='product',
            name='product_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=50),
        ),
        migrations.AlterField(
            model_name='product_brands',
            name='brand_description',
            field=models.TextField(blank=True, null=True, verbose_name='Brand Description'),
        ),
        migrations.AlterField(
            model_name='product_brands',
            name='brand_name',
            field=models.CharField(max_length=100, verbose_name='Brand Name'),
        ),
        migrations.AlterField(
            model_name='product_type',
            name='type',
            field=models.CharField(max_length=40, verbose_name='Product Type'),
        ),
        migrations.AddField(
            model_name='product',
            name='product_colors',
            field=models.ManyToManyField(to='products.product_colors'),
        ),
        migrations.AddField(
            model_name='product',
            name='product_flavours',
            field=models.ManyToManyField(to='products.product_flavours'),
        ),
        migrations.CreateModel(
            name='Product_Images',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_image', django_resized.forms.ResizedImageField(blank=True, crop=None, force_format=None, keep_meta=True, null=True, quality=-1, scale=None, size=[632, 632], upload_to=products.models.get_product_image_path)),
                ('product_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product')),
            ],
            options={
                'verbose_name': 'Product Image',
                'verbose_name_plural': 'Product Images',
            },
        ),
    ]
