# Generated by Django 5.0.1 on 2025-02-11 22:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_product_discount_brand_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product_discount',
            name='brand_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='brand_discount', to='products.product_brands'),
        ),
        migrations.AlterField(
            model_name='product_discount',
            name='category_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='category_discount', to='products.product_category'),
        ),
        migrations.AlterField(
            model_name='product_discount',
            name='product_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product_discount', to='products.product'),
        ),
        migrations.AlterField(
            model_name='product_discount',
            name='sub_category_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sub_category_discount', to='products.product_sub_category'),
        ),
        migrations.AlterField(
            model_name='product_sku',
            name='product_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product', to='products.product'),
        ),
    ]
