# Generated by Django 5.0.1 on 2025-02-12 17:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_alter_product_discount_brand_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product_discount',
            name='brand_id',
        ),
        migrations.RemoveField(
            model_name='product_discount',
            name='category_id',
        ),
        migrations.RemoveField(
            model_name='product_discount',
            name='sub_category_id',
        ),
    ]
