# Generated by Django 5.0.1 on 2025-01-17 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_remove_product_product_colors_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_category',
            field=models.ManyToManyField(related_name='products', to='products.product_category'),
        ),
    ]
