# Generated by Django 5.0.1 on 2025-02-12 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_remove_product_discount_brand_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product_sku',
            name='product_discounted_price',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=50, null=True),
        ),
    ]
