# Generated by Django 5.0.1 on 2025-02-12 17:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_product_sku_product_discounted_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product_sku',
            name='product_discounted_price',
        ),
    ]
