# Generated by Django 5.0.1 on 2025-01-17 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_alter_product_product_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_sub_category',
            field=models.ManyToManyField(related_name='products', to='products.product_sub_category'),
        ),
    ]
