# Generated by Django 5.0.1 on 2025-01-17 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_alter_product_product_sub_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_flavours',
            field=models.ManyToManyField(related_name='product_flavour', to='products.product_flavours'),
        ),
    ]
