# Generated by Django 5.0.1 on 2025-02-12 18:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_remove_product_sku_product_discounted_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='product_discount',
            name='brand_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='brand_discount', to='products.product_brands'),
        ),
        migrations.AddField(
            model_name='product_discount',
            name='category_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='category_discount', to='products.product_category'),
        ),
        migrations.AddField(
            model_name='product_discount',
            name='sub_category_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sub_category_discount', to='products.product_sub_category'),
        ),
    ]
