# Generated by Django 5.0.1 on 2025-01-19 10:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_alter_product_product_flavours'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product_sku',
            options={'verbose_name': 'Product SKU', 'verbose_name_plural': 'Products SKU'},
        ),
    ]
