# Generated by Django 5.0.1 on 2025-02-12 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_product_discount_brand_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product_discount',
            name='discount_name',
            field=models.CharField(max_length=100),
        ),
    ]
