# Generated by Django 5.0.1 on 2025-02-13 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_alter_product_discount_discount_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product_discount',
            name='brand_id',
        ),
        migrations.RemoveField(
            model_name='product_discount',
            name='category_id',
        ),
        migrations.RemoveField(
            model_name='product_discount',
            name='product_id',
        ),
        migrations.RemoveField(
            model_name='product_discount',
            name='sub_category_id',
        ),
        migrations.AddField(
            model_name='product_discount',
            name='brand_id',
            field=models.ManyToManyField(blank=True, null=True, related_name='brand_discount', to='products.product_brands'),
        ),
        migrations.AddField(
            model_name='product_discount',
            name='category_id',
            field=models.ManyToManyField(blank=True, null=True, related_name='category_discount', to='products.product_category'),
        ),
        migrations.AddField(
            model_name='product_discount',
            name='product_id',
            field=models.ManyToManyField(blank=True, null=True, related_name='product_discount', to='products.product'),
        ),
        migrations.AddField(
            model_name='product_discount',
            name='sub_category_id',
            field=models.ManyToManyField(blank=True, null=True, related_name='sub_category_discount', to='products.product_sub_category'),
        ),
    ]
