# Generated by Django 5.0.1 on 2025-01-21 12:01

import django_resized.forms
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_alter_product_sku_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product_brands',
            name='brand_logo',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format=None, keep_meta=True, null=True, quality=-1, scale=None, size=[244, 244], upload_to='brand_logos/'),
        ),
    ]
