# Generated by Django 5.0.1 on 2025-01-21 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_product_updated_by_product_brands_updated_by_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='updated_by',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='product_brands',
            name='updated_by',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='product_category',
            name='updated_by',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='product_discount',
            name='updated_by',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='product_flavours',
            name='updated_by',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='product_images',
            name='updated_by',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='product_review',
            name='updated_by',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='product_sku',
            name='updated_by',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='product_sub_category',
            name='updated_by',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='product_videos',
            name='updated_by',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
