# Generated by Django 5.0.1 on 2025-02-13 17:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_alter_product_discount_brand_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product_discount',
            name='brand_id',
        ),
        migrations.RemoveField(
            model_name='product_discount',
            name='category_id',
        ),
        migrations.RemoveField(
            model_name='product_discount',
            name='sub_category_id',
        ),
        migrations.AddField(
            model_name='product_discount',
            name='brand_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='brand_discount', to='products.product_brands'),
        ),
        migrations.AddField(
            model_name='product_discount',
            name='category_id',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, related_name='category_discount', to='products.product_category'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product_discount',
            name='sub_category_id',
            field=models.ForeignKey(blank=True, default=2, on_delete=django.db.models.deletion.CASCADE, related_name='sub_category_discount', to='products.product_sub_category'),
            preserve_default=False,
        ),
    ]
