# Generated by Django 5.0.1 on 2025-01-25 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0012_alter_product_updated_by_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product_images',
            name='color',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='product_images',
            name='size',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
