# Generated by Django 5.0.1 on 2025-02-13 17:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0012_remove_product_discount_brand_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product_discount',
            name='category_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='category_discount', to='products.product_category'),
        ),
        migrations.AlterField(
            model_name='product_discount',
            name='sub_category_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sub_category_discount', to='products.product_sub_category'),
        ),
    ]
