# Generated by Django 5.0.1 on 2025-02-13 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0013_alter_product_discount_category_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product_discount',
            name='brand_id_pk',
            field=models.BigIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='product_discount',
            name='category_id_pk',
            field=models.BigIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='product_discount',
            name='product_id_pk',
            field=models.BigIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='product_discount',
            name='sub_category_id_pk',
            field=models.BigIntegerField(blank=True, default=0, null=True),
        ),
    ]
