# Generated by Django 5.0.1 on 2025-01-26 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0013_alter_product_images_color_alter_product_images_size'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='product_flavours',
        ),
        migrations.AddField(
            model_name='product_sku',
            name='product_flavours',
            field=models.ManyToManyField(related_name='product_flavour', to='products.product_flavours'),
        ),
    ]
