# Generated by Django 5.0.1 on 2025-01-26 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0014_remove_product_product_flavours_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product_discount',
            name='discount_name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
