# Generated by Django 5.0.1 on 2025-02-13 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0014_product_discount_brand_id_pk_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product_discount',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
