# Generated by Django 5.0.1 on 2025-02-14 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0015_product_discount_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='product_discount',
            name='existing_discounts',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
