# Generated by Django 5.0.1 on 2025-02-15 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0016_product_discount_existing_discounts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product_discount',
            name='end_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='product_discount',
            name='start_date',
            field=models.DateField(),
        ),
    ]
