# Generated by Django 5.0.1 on 2025-02-15 20:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0017_alter_product_discount_end_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product_discount',
            name='existing_discounts',
        ),
    ]
