# Generated by Django 5.0.1 on 2025-03-13 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0018_remove_product_discount_existing_discounts'),
    ]

    operations = [
        migrations.AddField(
            model_name='product_sku',
            name='product_gender',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
