# Generated by Django 5.0.1 on 2025-01-15 13:14

import customer.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='block',
            field=models.BooleanField(default=False, verbose_name='Block Customer'),
        ),
        migrations.AddField(
            model_name='customer',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to=customer.models.get_customer_avatar, verbose_name='Profile Picture'),
        ),
        migrations.AddField(
            model_name='customer',
            name='unique_id',
            field=models.CharField(default=1, max_length=50, unique=True, verbose_name='Unique ID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customer',
            name='username',
            field=models.CharField(default=2, max_length=50, unique=True, verbose_name='Username'),
            preserve_default=False,
        ),
    ]
