# Generated by Django 5.0.1 on 2025-01-20 11:16

import customer.models
import django_resized.forms
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0004_rename_phone_customer_phone_no_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='profile_picture',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format=None, keep_meta=True, null=True, quality=-1, scale=None, size=[244, 244], upload_to=customer.models.get_customer_avatar_path),
        ),
    ]
