# Generated by Django 5.0.1 on 2025-01-26 23:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0006_customeruser'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customeruser',
            name='username',
        ),
    ]
