# Generated by Django 5.0.1 on 2025-01-27 13:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0008_customeruser'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomerUser',
        ),
    ]
